services:
  - type: web
    name: scotch
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SCOTCH_DB_PATH
        value: /var/data/scotch.db
    disk:
      name: scotch-data
      mountPath: /var/data
      sizeGB: 1
